### ISSUE TITLE
missing files qc/fb-contrib-6.2.0.jar, qc/findsecbugs-plugin-1.4.1.jar

### ISSUE THREAD

**Issue by amaurya72** [gualtierotesta/code-quality-gallery#1]
Thanks for putting together a simple project showcasing FindBugs plugin. 
When I compile the project, I did get an error: Could not find resource 'qc/fb-contrib-6.2.0.jar'

Can you please let us know how to get the missing files fb-contrib-6.2.0.jar, findsecbugs-plugin-1.4.1.jar

-anand

**Comment by gualtierotesta** [comment]
Thanks for reporting the issue. I committed the missing files.

FB Contrib plugin can be also downloaded from http://fb-contrib.sourceforge.net/

Find Security plugin from https://find-sec-bugs.github.io/
