### ISSUE TITLE
Looking for help

### ISSUE THREAD

**Issue by amaurya72** [gualtierotesta/code-quality-gallery#2]
Have been struggling to get findbugs working for me.
running your code after downloading from git using the command "mvn package findbugs:findbugs" 

I am running into an error shown below. 
Can you let me know how did you resolve this problem. This is the exact same error I am getting with my own project to.

One thing i found is that if a required property is not set, findbugs plugin is failing.

Wanted to check with you if you can let me know if your code is working as it is.

C:\Users\amaurya.ORADEV\workspace\eclipse\neon\code-quality-gallery-master>mvn package findbugs:findbugs
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building CodeQualityGallery 1.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ CodeQualityGallery ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\amaurya.ORADEV\workspace\eclipse\neon\code-quality-gallery-master\src\main\resou
rces
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ CodeQualityGallery ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ CodeQualityGallery ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\amaurya.ORADEV\workspace\eclipse\neon\code-quality-gallery-master\src\test\resou
rces
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ CodeQualityGallery ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ CodeQualityGallery ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ CodeQualityGallery ---
[INFO]
[INFO] --- findbugs-maven-plugin:3.0.1:findbugs (default-cli) @ CodeQualityGallery ---
[INFO] Fork Value is true
     [java] Error: Could not find or load main class edu.umd.cs.findbugs.FindBugs2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.274 s
[INFO] Finished at: 2016-10-17T15:01:09-07:00
[INFO] Final Memory: 23M/250M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.1:findbugs (default-cli) on project CodeQualityGallery: E
xecution default-cli of goal org.codehaus.mojo:findbugs-maven-plugin:3.0.1:findbugs failed: Java returned: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by gualtierotesta** [comment]
Please check you are not using a JRE (may be the Eclipse one) but a JDK.
From the command line run the `mvn -v` command. You should get something like:

```
mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/gualtiero/.sdkman/candidates/maven/current
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_92/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-43-generic", arch: "amd64", family: "unix"
```

I have attached my log of the `mvn package findbugs:findbugs` for you to compare

[log.txt](https://github.com/gualtierotesta/code-quality-gallery/files/538018/log.txt)

**Comment by amaurya72** [comment]
Thanks for the updated libraries. Looks like the repo url I am using has some issue. When I switched to maven central it worked. Need to figure out what is going on. Thanks for your help.
